---
name: MooseX-Param
version: 0.01
author:
  - 'Stevan Little E<lt>stevan@iinteractive.comE<gt>'
abstract: Simple role to provide a standard param method
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Moose: 0.17
build_requires:
  Test::Exception: 0.21
  Test::More: 0.62
provides:
  MooseX::Param:
    file: lib/MooseX/Param.pm
    version: 0.01
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
